Week3_FormCreation/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Week3_FormCreation.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Week3_FormCreation.Controllers
{
    public class AboutUsController: Controller
    {

        public IActionResult Index()
        {
            AboutUs aboutUs = new AboutUs
            {
                Title = "Pizza dots",
            Body = "Pizza dots opened its doors with one goal in mind: Better Pizza." +
            " We knew that with best ingredients we would create better pizzas. That goal and the promise of " +
            "best ingredients, better pizza remain true always."
        };
          

            return View(aboutUs);
        }
    }
}

Week3_FormCreation/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DAL;
using DataModels;
using Library.BusinessLogic;
using System.Configuration;
using Microsoft.Extensions.Configuration;
using Week3_FormCreation.Models;

using Microsoft.AspNetCore.Http;

namespace Week3_FormCreation.Controllers
{
    public class AdminController : Controller
    {
        
        public IActionResult AdminControlPanel()
        {
            // CHECK LOGIN SESSION!
            var var_chk_session = HttpContext.Session.GetString("AdminLogin");
            if (var_chk_session is null)
            {
                return RedirectToAction("Index");
                
            }
            else
            {
                if(var_chk_session.ToString().Equals("true"))
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
                
            }
            
        }

        public IActionResult SignOut()
        {
            // CHECK LOGIN SESSION!
            var var_chk_session = HttpContext.Session.GetString("AdminLogin");
            if (var_chk_session is null)
            {
                return RedirectToAction("Index");

            }
            else
            {
                if (var_chk_session.ToString().Equals("true"))
                {
                    HttpContext.Session.SetString("AdminLogin", "false");
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

        }




        public IActionResult Index()
        {
            // CHECK LOGIN SESSION!
            var var_chk_session = HttpContext.Session.GetString("AdminLogin");
            if (var_chk_session is null)
            {
                return View();

            }
            else
            {
                if (var_chk_session.ToString().Equals("true"))
                {
                    return RedirectToAction("AdminControlPanel");
                }
                else
                {
                    return View();
                }

            }

        }

        [HttpPost]
        public IActionResult Index(AdminLogin adminlogin)
        {

            // Create A Has Password in DB
            if (ModelState.IsValid)
            {
                if (adminlogin.adminLoginId == null || adminlogin.adminLoginPwd == null)
                {
                    return View(adminlogin);
                }
                // CHK DB TO GET ADMIN STORED PWD SALT AND HASH & LOGIN ID
                // CHK LOGIN
                AdminLogin login = new AdminLogin();
                
                bool chk_login_result = login.CheckLogin(adminlogin);
                
                if(chk_login_result)
                {
                    HttpContext.Session.SetString("AdminLogin", "true");
                    adminlogin.adminMsg = "Login Succesful!";
                    return RedirectToAction("AdminControlPanel");
                }
                else
                {
                    adminlogin.adminMsg = "Invalid User Name or Pwd?";
                    return View(adminlogin);

                }

            }
             return View(adminlogin);           
        }

    }
    
}

Week3_FormCreation/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataModels;
using Library.BusinessLogic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Week3_FormCreation.Models;

namespace Week3_FormCreation.Controllers
{
    public class CartController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Add(String MenuId, String StoreId)
        {
            // CHECK CART SESSIONID VARIABLE.
            var var_chk_session = HttpContext.Session.GetString("CartSessionId");
            if (var_chk_session is null)
            {
                // IF NULL THEN CREATE NEW GUID & ASSIGN THE SESSION
                Guid guid = Guid.NewGuid();
                // CREATE GUID & SESSION VARIABLE - CART SESSION ID.

                HttpContext.Session.SetString("CartSessionId", guid.ToString());
              

            }

            // GET THE ITEM DETAILS FROM DB FOR THE CART
            StoreMenuHandler handler = new StoreMenuHandler();
            var storeitemdetails = handler.GetStoreItemDetails(int.Parse(StoreId),int.Parse(MenuId));

            // CHECK WHETHER THAT ITEM EXISTS IN CART THEN UPDATE ONLY QUANTITY.
            CartHandler chkcartitemexists = new CartHandler();
            var alreadyitemexistincart = chkcartitemexists.GetIteminCart(HttpContext.Session.GetString("CartSessionId").ToString(), int.Parse(StoreId), int.Parse(MenuId));
            // ITEM EXISTS IN CART
            if(alreadyitemexistincart.Count()>0)
            {
                // UPDATE THE ITEM QTY IN CART AT THE CART_ID FIELD
                CartHandler cart_item_upd = new CartHandler();
                // INCREMENT QTY BY 1 ++
                alreadyitemexistincart[0].Cart_qty = alreadyitemexistincart[0].Cart_qty +1;
                alreadyitemexistincart[0].Cart_menu_price = alreadyitemexistincart[0].Cart_qty*alreadyitemexistincart[0].Cart_menu_price;
                var cartitemupd = cart_item_upd.UpdateCartItemQty(alreadyitemexistincart[0]);

            }
            else
            {
                // INSERT THE ITEM IN THE CART
                CartHandler cartinsertitem = new CartHandler();
                Cart crtitm = new Cart();
                crtitm.Cart_session_id = HttpContext.Session.GetString("CartSessionId").ToString();
                crtitm.Cart_menu = storeitemdetails[0].Pizza_Menu;
                crtitm.Cart_menu_id = storeitemdetails[0].Pizza_Menu_Id;
                crtitm.Cart_menu_price = storeitemdetails[0].Pizza_Menu_Price;
                crtitm.Cart_qty = 1;
                crtitm.Cart_store_id = storeitemdetails[0].Pizza_Store_Id;
                var cartitmins = cartinsertitem.InsertCartItem(crtitm);

            }
            
            return View(storeitemdetails);            
        }

        public IActionResult ViewCart(String MenuId, String StoreId)
        {
            // CHECK CART SESSIONID VARIABLE.
            var var_chk_session = HttpContext.Session.GetString("CartSessionId");
            var var_chk_cart_empty = HttpContext.Session.GetString("CartSessionEmpty");
            if (var_chk_session is null)
            {
                return RedirectToAction("Index");
            }

            // GET THE ITEM DETAILS FROM DB FOR THE CART
           CartHandler handler = new CartHandler();
           var getallitemsincart = handler.ViewCartItems(HttpContext.Session.GetString("CartSessionId").ToString());
            if(getallitemsincart is null)
            {
                return RedirectToAction("Index");
            }
            // GET TOTAL OF CART ITEMS
            var getcarttotal = handler.GetCartSubTotal(HttpContext.Session.GetString("CartSessionId").ToString());
            // SET TOTAL IN [getallitemsincart] object for VIEW
            foreach (var item in getallitemsincart)
            {
                item.Cart_Total = getcarttotal[0].Cart_Sub_Total + (getcarttotal[0].Cart_Sub_Total * 13)/100;
                item.Cart_Sub_Total = getcarttotal[0].Cart_Sub_Total;
                item.Cart_Total_Tax = (getcarttotal[0].Cart_Sub_Total * 13) / 100;
            }

            // SET THE TOTAL IN THE SESSION VARIABLE FOR PAYMENT....
            HttpContext.Session.SetString("CartTotal", (getcarttotal[0].Cart_Sub_Total + (getcarttotal[0].Cart_Sub_Total * 13) / 100).ToString("0.00"));
            return View(getallitemsincart);
        }

        public IActionResult EmptyCart()
        {
            // CHECK CART SESSIONID VARIABLE.
            var var_chk_session = HttpContext.Session.GetString("CartSessionId");
            if (var_chk_session is null)
            {
                return View();
            }

            // GET THE ITEM DETAILS FROM DB FOR THE CART
            CartHandler handler = new CartHandler();
            var emptycart = handler.EmptyCart(HttpContext.Session.GetString("CartSessionId").ToString());
            
            return View();
        }

        [Authorize]
        public IActionResult Payment()
        {
            // CHECK CART SESSIONID VARIABLE.
            var var_chk_session = HttpContext.Session.GetString("CartSessionId");
            var var_chk_cart_total = HttpContext.Session.GetString("CartTotal");
            if ((var_chk_session is null) || (var_chk_cart_total is null))
            {
                return RedirectToAction("Index");

            }
            return View();
        }

        [HttpPost]
        public IActionResult Payment(Payment payment)
        {
            // CHECK CART SESSIONID VARIABLE.
            var var_chk_session = HttpContext.Session.GetString("CartSessionId");
            var var_chk_cart_total = HttpContext.Session.GetString("CartTotal");
            if ((var_chk_session is null) || (var_chk_cart_total is null))
            {
                return RedirectToAction("Index");

            }
            CartHandler handler = new CartHandler();
            var emptycart = handler.EmptyCart(HttpContext.Session.GetString("CartSessionId").ToString());
            HttpContext.Session.SetString("OrderId", HttpContext.Session.GetString("CartSessionId").ToString());
            HttpContext.Session.Remove("CartSessionId");
            return View("PaymentConfirmation");
        }
    }

}

Week3_FormCreation/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.BusinessLogic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Week3_FormCreation.Models;

namespace Week3_FormCreation.Controllers
{
    public class DeliveryController : Controller
    {
        public IActionResult DeliveryUserPanel()
        {
            // CHECK LOGIN SESSION!
            var var_chk_session = HttpContext.Session.GetString("DeliveryLogin");
            if (var_chk_session is null)
            {
                return RedirectToAction("Index");

            }
            else
            {
                if (var_chk_session.ToString().Equals("true"))
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }

        }
        public IActionResult SignOut()
        {
            // CHECK LOGIN SESSION!
            var var_chk_session = HttpContext.Session.GetString("DeliveryLogin");
            if (var_chk_session is null)
            {
                return RedirectToAction("Index");

            }
            else
            {
                if (var_chk_session.ToString().Equals("true"))
                {
                    HttpContext.Session.SetString("DeliveryLogin", "false");
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

        }
        public IActionResult Index()
        {
            // CHECK LOGIN SESSION!
            var var_chk_session = HttpContext.Session.GetString("DeliveryLogin");
            if (var_chk_session is null)
            {
                return View();

            }
            else
            {
                if (var_chk_session.ToString().Equals("true"))
                {
                    return RedirectToAction("DeliveryUserPanel");
                }
                else
                {
                    return View();
                }

            }

        }

        [HttpPost]
        public IActionResult Index(DeliveryLogin deliverylogin)
        {

            // Create A Has Password in DB
            if (ModelState.IsValid)
            {
                if (deliverylogin.deliveryLoginId == null || deliverylogin.deliveryLoginPwd == null)
                {
                    return View(deliverylogin);
                }
                // CHK DB TO GET DELIVERY STORED PWD SALT AND HASH & LOGIN ID
                // CHK LOGIN
                DeliveryLogin login = new DeliveryLogin();

                bool chk_login_result = login.CheckLogin(deliverylogin);

                if (chk_login_result)
                {
                    HttpContext.Session.SetString("DeliveryLogin", "true");
                    deliverylogin.deliveryMsg = "Login Succesful!";
                    return RedirectToAction("DeliveryUserPanel");
                }
                else
                {
                    deliverylogin.deliveryMsg = "Invalid User Name or Pwd?";
                    return View(deliverylogin);

                }

            }
            return View(deliverylogin);
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(Week3_FormCreation.Models.DeliveryRegister deliveryregister)
        {

            // CHECK ALL THE REGISTERATION PARAMETERS
            if (ModelState.IsValid)
            {

                // CHECK THE STATUS ALL FIELDS ARE COMPLETE.
                if (deliveryregister.deliveryRegisterLoginEmailId == null || deliveryregister.deliveryRegisterLoginPwdFirst == null || deliveryregister.deliveryRegisterLoginPwdRepeat == null)
                {
                    return View(deliveryregister);
                }

                // INITATE DELIVERY REGISTER.
                DeliveryRegister register = new DeliveryRegister();

                // CHK USER_LOGIN EXISTS-> ID AVAILABLE
                DataModels.DeliveryRegister delivery_register = new DataModels.DeliveryRegister();
                delivery_register.Delivery_Login_Id = deliveryregister.deliveryRegisterLoginEmailId;
                bool isIDAlreadyExist = register.CheckLoginIdExists(delivery_register);

                if(isIDAlreadyExist)
                {
                    deliveryregister.deliveryRegisterMsg = "User Email Id Already Exists!";
                    return View(deliveryregister);
                }


                // CHK PWD_REPEAT & STRENGTH (ATLEAST 1 CAPITAL,LENGTH:8,1 SYMBOL (@#$`!),NUMBER 1)
                bool pwd_strengthMatch = register.CheckPasswordStrengthMatch(deliveryregister.deliveryRegisterLoginPwdFirst, deliveryregister.deliveryRegisterLoginPwdRepeat);

                if(pwd_strengthMatch==false)
                {
                    deliveryregister.deliveryRegisterMsg = "Password Not Matching / No Passord Strength Criteria Followed!";
                    return View(deliveryregister);
                }

                // GET THE HASH PASSWORD AND SALT
                HashSalt hash =  HashSalt.GenerateSaltedHash(64, deliveryregister.deliveryRegisterLoginPwdFirst);


                // NOW EVERYTHING FINE THEN ADD THE DELIVERY USER REGISTER DETAILS TO THE DB...
                delivery_register.Delivery_Login_Id = deliveryregister.deliveryRegisterLoginEmailId;
                delivery_register.Delivery_Pwd_Hash = hash.Hash;
                delivery_register.Delivery_Pwd_Salt = hash.Salt;
                delivery_register.Delivery_User_Address = deliveryregister.deliveryRegisterUserAddress;
                delivery_register.Delivery_User_City = deliveryregister.deliveryRegisterUserCity;
                delivery_register.Delivery_User_Firstname = deliveryregister.deliveryRegisterUserFirstName;
                delivery_register.Delivery_User_Lastname = deliveryregister.deliveryRegisterUserLastName;
                delivery_register.Delivery_User_Phoneno = deliveryregister.deliveryRegisterUserPhoneNo;
                delivery_register.Delivery_User_Postalcode = deliveryregister.deliveryRegisterUserPostalCode;
                delivery_register.Delivery_User_Province = deliveryregister.deliveryRegisterUserProvince;

                // ADD THE REGISTER DELIVERY USER TO DB...
                DeliveryRegisterHandler handler = new DeliveryRegisterHandler();
                var newregisteruser = handler.AddDeliveryRegister(delivery_register);

                deliveryregister.deliveryRegisterMsg = "User Added Succesfully! Please Login";
                
            

                return View(deliveryregister);
            }
            
            return View(deliveryregister);
        }
    }
}

Week3_FormCreation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Dots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Syncfusion Essential JS 2 Styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">View Cart</a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="Index">Delivery Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutUs" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                        </li>            
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Pizza Dots - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <!-- Syncfusion Essential JS 2 ScriptManager -->
    <ejs-scripts></ejs-scripts>

</body>
</html>

Week3_FormCreation/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Dots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Syncfusion Essential JS 2 Styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index"><img src="~/images/logo.png" /> Admin ControlPanel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Pizza Dots - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <!-- Syncfusion Essential JS 2 ScriptManager -->
    <ejs-scripts></ejs-scripts>

</body>
</html>

Week3_FormCreation/Views/Shared/_LayoutAdminLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Dots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Syncfusion Essential JS 2 Styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index"><img src="~/images/logo.png" /> Admin Login</a>
             </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Week3_FormCreation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <!-- Syncfusion Essential JS 2 ScriptManager -->
    <ejs-scripts></ejs-scripts>

</body>
</html>

Week3_FormCreation/Views/Shared/_LayoutDeliveryAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Dots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Syncfusion Essential JS 2 Styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Delivery" asp-action="Index"><img src="~/images/logo.png" /> Admin ControlPanel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="ViewOrders">View Delivery Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="PaymentInfo">Payment Information</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="Profile">Profile</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Pizza Dots - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <!-- Syncfusion Essential JS 2 ScriptManager -->
    <ejs-scripts></ejs-scripts>

</body>
</html>